"""
--- Day 7: Laboratories ---

You thank the cephalopods for the help and exit the trash compactor, finding yourself in the familiar halls of a North Pole research wing.

Based on the large sign that says "teleporter hub", they seem to be researching teleportation; you can't help but try it for yourself and step onto the large yellow teleporter pad.

Suddenly, you find yourself in an unfamiliar room! The room has no doors; the only way out is the teleporter. Unfortunately, the teleporter seems to be leaking magic smoke.

Since this is a teleporter lab, there are lots of spare parts, manuals, and diagnostic equipment lying around. After connecting one of the diagnostic tools, it helpfully displays error code 0H-N0, which apparently means that there's an issue with one of the tachyon manifolds.

You quickly locate a diagram of the tachyon manifold (your puzzle input). A tachyon beam enters the manifold at the location marked S; tachyon beams always move downward. Tachyon beams pass freely through empty space (.). However, if a tachyon beam encounters a splitter (^), the beam is stopped; instead, a new tachyon beam continues from the immediate left and from the immediate right of the splitter.

For example:

.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............

In this example, the incoming tachyon beam (|) extends downward from S until it reaches the first splitter:

.......S.......
.......|.......
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............

At that point, the original beam stops, and two new beams are emitted from the splitter:

.......S.......
.......|.......
......|^|......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............

Those beams continue downward until they reach more splitters:

.......S.......
.......|.......
......|^|......
......|.|......
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............

At this point, the two splitters create a total of only three tachyon beams, since they are both dumping tachyons into the same place between them:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............

This process continues until all of the tachyon beams reach a splitter or exit the manifold:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
.....|.|.|.....
....|^|^|^|....
....|.|.|.|....
...|^|^|||^|...
...|.|.|||.|...
..|^|^|||^|^|..
..|.|.|||.|.|..
.|^|||^||.||^|.
.|.|||.||.||.|.
|^|^|^|^|^|||^|
|.|.|.|.|.|||.|

To repair the teleporter, you first need to understand the beam-splitting properties of the tachyon manifold. In this example, a tachyon beam is split a total of 21 times.

Analyze your manifold diagram. How many times will the beam be split?
"""

from collections import defaultdict

ENTER = "S"
SPLITTER = "^"
SPACE = "."


def collect_line(line: str, beam_coodinates: dict[int, list[int]], y: int) -> int:
    """
    Keep track of the beam coordinates and the splits.
    Once split hits a splitter, add the coordinates of the beam to the list.
    Also, add coordinates of the beams from above and check if splitters
    are not next to each other.
    """
    splits_hit = 0

    for i, char in enumerate(line):
        if i in beam_coodinates.get(y - 1, []):
            if char == SPLITTER:
                if i > 0 and line[i - 1] != SPLITTER:
                    beam_coodinates[y].append(i - 1)
                if i < len(line) - 1 and line[i + 1] != SPLITTER:
                    beam_coodinates[y].append(i + 1)
                splits_hit += 1
            if char == SPACE:
                beam_coodinates[y].append(i)

    return splits_hit


def process_input(input_path: str) -> int:
    total_splits = 0
    beam_coodinates: dict[int, list[int]] = defaultdict(list)  # y: [x, x, ...], y: [x, x, ...]

    try:
        with open(input_path, encoding="utf-8") as f:
            lines = f.readlines()

        enter_coordinate = lines[0].index(ENTER)
        beam_coodinates[1] = [enter_coordinate]

        for i, line in enumerate(lines[2:]):
            line = line.strip("\n")
            if not line:
                continue

            total_splits += collect_line(line, beam_coodinates, i + 2)

    except FileNotFoundError:
        return 0

    return total_splits


if __name__ == "__main__":
    # print(f"Tachyon beam will split: {process_input("day7/test_input.txt")}")
    print(f"Tachyon beam will split: {process_input("day7/input.txt")}")
    # Tachyon beam will split: 1626
    #
    # I was about to give up on this one because didn't
    # have a clever solution right from the start and
    # that kind of frustrated me.
    #
    # But I took some time off the screen to reflect
    # on the problem and got it right.
    #
    # Lesson learned from AoC: Don't rush to the solution.
